# Write a Python program to create a list with elements of multiple data types (integers, strings, floats, etc.).
my_list = [42, "Hello", 3.14, True, [1, 2, 3]]
print(type(my_list))


# Write a Python program to access elements at different index positions.

print("Element at index 0  :", my_list[0])
print("Element at index -1 :", my_list[-1])
print("Element at index 2  :", my_list[2])

# 1. Write a Python program to create a list of multiple data type elements.

list = [10, "Python", 4.56, False, None]
print("Created list:", list)


# 2. Write a Python program to find the length of a list using the len() function.
length = len(list)
print("Length of the list:", length)

